package com.bullPenTalk.app.dto;

public class AdminPostDTO {
//	CREATE TABLE tbl_admin_post(
//	admin_number number,
//	post_number NUMBER,
//	CONSTRAINT PK_ADMIN_POST PRIMARY KEY(ADMIN_NUMBER, POST_NUMBER),
//	CONSTRAINT FK_POST_ADMIN_NUMBER FOREIGN KEY (ADMIN_NUMBER) REFERENCES TBL_ADMIN (ADMIN_NUMBER),
//	CONSTRAINT FK_ADMIN_POST_NUMBER FOREIGN KEY (POST_NUMBER) REFERENCES TBL_POST (POST_NUMBER) ON DELETE CASCADE
//	);
}
