package com.bullPenTalk.app.dto;

public class AttachmentDTO {
//	CREATE TABLE TBL_ATTACHMENT(
//	ATTACHMENT_NUMBER NUMBER,
//	ATTACHMENT_TYPE_ID NUMBER,
//	ATTACHMENT_NAME VARCHAR2(100),
//	ATTACHMENT_SIZE NUMBER,
//	ATTACHMENT_PATH VARCHAR2(200),
//	CONSTRAINT PK_ATTACHMENT PRIMARY KEY(ATTACHMENT_NUMBER),
//	CONSTRAINT FK_ATTACHMENT_TYPE FOREIGN KEY(ATTACHMENT_TYPE_ID) REFERENCES TBL_ATTACHMENT_TYPE(ATTACHMENT_TYPE_ID)
//	);
}
