package com.bullPenTalk.app.dto;

public class AttachmentTypeDTO {
//	CREATE TABLE TBL_ATTACHMENT_TYPE(
//	ATTACHMENT_TYPE_ID NUMBER,
//	ATTACHMENT_TYPE VARCHAR2(50),
//	CONSTRAINT PK_ATTACHMENT_TYPE PRIMARY KEY(ATTACHMENT_TYPE_ID)
//	);
}
