package com.bullPenTalk.app.dto;

public class BoardDTO {
//	CREATE TABLE TBL_BOARD(
//	BOARD_NUMBER NUMBER,
//	BOARD_ID NUMBER,
//	CONSTRAINT PK_BOARD PRIMARY KEY(BOARD_NUMBER),
//	CONSTRAINT FK_BOARD FOREIGN KEY(BOARD_ID) REFERENCES TBL_BOARD_TYPE(BOARD_TYPE_ID)
//	);
}
