package com.bullPenTalk.app.dto;

public class BoardTypeDTO {
//	CREATE TABLE TBL_BOARD_TYPE(
//	BOARD_TYPE_ID NUMBER,
//	BOARD_TYPE_NAME VARCHAR2(50) NOT NULL,
//	CONSTRAINT PK_BOARD_TYPE PRIMARY KEY(BOARD_TYPE_ID)
//	);
}
