package com.bullPenTalk.app.dto;

public class ChampionshipRecordDTO {
//	CREATE TABLE TBL_CHAMPIONSHIP_RECORD (
//	TEAM_NUMBER       NUMBER NOT NULL,
//	SEASON_YEAR       NUMBER NOT NULL,
//	IS_CHAMPIONSHIP   CHAR(1) CHECK (IS_CHAMPIONSHIP IN ('Y', 'N')),
//	CONSTRAINT PK_CHAMPIONSHIP PRIMARY KEY (TEAM_NUMBER, SEASON_YEAR),
//	CONSTRAINT FK_CHAMPIONSHIP_TEAM FOREIGN KEY (TEAM_NUMBER) REFERENCES TBL_TEAM(TEAM_NUMBER)
//	);
}
