package com.bullPenTalk.app.dto;

public class CommentDTO {
//	CREATE TABLE TBL_COMMENT(
//	COMMENT_NUMBER NUMBER,
//	MEMBER_NUMBER NUMBER NOT NULL,
//	POST_NUMBER NUMBER NOT NULL,
//	COMMENT_CONTENT VARCHAR2(2000) NOT NULL,
//	COMMENT_DATE DATE NOT NULL DEFAULT SYSDATE ,
//	COMMENT_UPDATE DATE NOT NULL,
//	CONSTRAINT PK_COMMENT PRIMARY KEY(COMMENT_NUMBER),
//	CONSTRAINT FK_COMMENT_MEMBER FOREIGN KEY(MEMBER_NUMBER) REFERENCES TBL_MEMBER(MEMBER_NUMBER) ON DELETE CASCADE,
//	CONSTRAINT FK_COMMENT_POST FOREIGN KEY(POST_NUMBER) REFERENCES TBL_POST(POST_NUMBER) ON DELETE CASCADE
//	);
}
