package com.bullPenTalk.app.dto;

public class GameScheduleDTO {
//	CREATE TABLE TBL_GAME_SCHEDULE (
//	GAME_ID            NUMBER PRIMARY KEY,
//	HOME_TEAM_NUMBER   NUMBER NOT NULL,
//	AWAY_TEAM_NUMBER   NUMBER NOT NULL,
//	SCHEDULE_DATE      DATE NOT NULL,
//	STADIUM_NUMBER     NUMBER NOT NULL,
//	CONSTRAINT FK_HOME_TEAM FOREIGN KEY (HOME_TEAM_NUMBER) REFERENCES TBL_TEAM(TEAM_NUMBER),
//	CONSTRAINT FK_AWAY_TEAM FOREIGN KEY (AWAY_TEAM_NUMBER) REFERENCES TBL_TEAM(TEAM_NUMBER),
//	CONSTRAINT FK_STADIUM FOREIGN KEY (STADIUM_NUMBER) REFERENCES TBL_STADIUM(STADIUM_NUMBER)
//	);
}
