package com.bullPenTalk.app.dto;

public class MatchResultDTO {
//	CREATE TABLE TBL_MATCH_RESULT (
//	GAME_ID          NUMBER PRIMARY KEY,
//	HOME_TEAM_SCORE  NUMBER,
//	AWAY_TEAM_SCORE  NUMBER,
//	MATCH_RESULT     VARCHAR2(10),
//	CONSTRAINT FK_MATCH_GAME FOREIGN KEY (GAME_ID) REFERENCES TBL_GAME_SCHEDULE(GAME_ID)
//	);
}
