package com.bullPenTalk.app.dto;

public class NoticeTypeDTO {
//	CREATE TABLE TBL_NOTICE_TYPE(
//	NOTICE_TYPE_ID NUMBER,
//	NOTICE_TYPE VARCHAR2(50) NOT NULL,
//	CONSTRAINT PK_NOTICE_TYPE PRIMARY KEY(NOTICE_TYPE_ID)
//	);
}
