package com.bullPenTalk.app.dto;

public class NoticePostDTO {
//	CREATE TABLE TBL_NOTICE_POST(
//	NOTICE_POST_NUMBER NUMBER,
//	NOTICE_TYPE_ID NUMBER,
//	ADMIN_NUMBER NUMBER,
//	TEAM_NUMBER NUMBER,
//	NOTICE_POST_TITLE VARCHAR2(100) NOT NULL,
//	NOTICE_POST_CONTENT CLOB NOT NULL,
//	NOTICE_POST_DATE DATE NOT NULL,
//	NOTICE_POST_UPDATE DATE ,
//	CONSTRAINT PK_NOTICE_POST PRIMARY KEY(NOTICE_POST_NUMBER),
//	CONSTRAINT FK_NOTICE_POST_ADMIN FOREIGN KEY(ADMIN_NUMBER) REFERENCES TBL_ADMIN(ADMIN_NUMBER),
//	CONSTRAINT FK_NOTICE_POST_TYPE FOREIGN KEY(NOTICE_TYPE_ID) REFERENCES TBL_NOTICE_TYPE(NOTICE_TYPE_ID),
//	CONSTRAINT FK_NOTICE_POST_TEAM FOREIGN KEY(TEAM_NUMBER) REFERENCES TBL_TEAM (TEAM_NUMBER)
//	);
}
