package com.bullPenTalk.app.dto;

public class PlayerDTO {
//	CREATE TABLE TBL_PLAYER(
//	PLAYER_NUMBER NUMBER,
//	TEAM_NUMBER NUMBER NOT NULL,
//	PLAYER_POSITION VARCHAR2(15) NOT NULL,
//	PLAYER_NAME VARCHAR2(30) NOT NULL,
//	CONSTRAINT PK_PLAYER PRIMARY KEY(PLAYER_NUMBER),
//	CONSTRAINT FK_PLAYER_TEAM FOREIGN KEY(TEAM_NUMBER) REFERENCES TBL_TEAM(TEAM_NUMBER)
//	);
}
