package com.bullPenTalk.app.dto;

public class StadiumTicketDTO {
//	CREATE TABLE TBL_STADIUM_TICKET (
//	TICKET_ID        NUMBER PRIMARY KEY,
//	STADIUM_NUMBER   NUMBER NOT NULL,
//	TEAM_NUMBER      NUMBER NOT NULL,
//	SEAT_NAME        VARCHAR2(50) NOT NULL,
//	WEEKDAY_PRICE    NUMBER NOT NULL,
//	WEEKEND_PRICE    NUMBER NOT NULL,
//	RESERVATION_SITE VARCHAR2(50) NOT NULL,
//	CONSTRAINT FK_TICKET_STADIUM FOREIGN KEY (STADIUM_NUMBER) REFERENCES TBL_STADIUM(STADIUM_NUMBER) ON DELETE CASCADE,
//	CONSTRAINT FK_TICKET_TEAM FOREIGN KEY (TEAM_NUMBER) REFERENCES TBL_TEAM(TEAM_NUMBER)ON DELETE CASCADE
//	);
}
