package com.bullPenTalk.app.dto;

public class StadiumFoodDTO {
//	CREATE TABLE TBL_STADIUM_FOOD (
//	FOOD_ID         NUMBER PRIMARY KEY,
//	FOOD_NAME       VARCHAR2(200) NOT NULL,
//	FOOD_LOCATION   VARCHAR2(100) NOT NULL,
//	FOOD_TIP        VARCHAR2(200) NOT NULL,
//	STADIUM_NUMBER  NUMBER NOT NULL,
//	CONSTRAINT FK_FOOD_STADIUM FOREIGN KEY (STADIUM_NUMBER) REFERENCES TBL_STADIUM(STADIUM_NUMBER)ON DELETE CASCADE
//	);
}
