package com.bullPenTalk.app.dto;

public class StadiumDTO {
//	CREATE TABLE TBL_STADIUM (
//	STADIUM_NUMBER   NUMBER PRIMARY KEY,
//	STADIUM_ADDRESS  VARCHAR2(100) NOT NULL,
//	STADIUM_NAME     VARCHAR2(50) NOT NULL,
//	TEAM_NUMBER      NUMBER NOT NULL,
//	CONSTRAINT FK_STADIUM_TEAM FOREIGN KEY (TEAM_NUMBER) REFERENCES TBL_TEAM(TEAM_NUMBER)
//	);
}
