package com.bullPenTalk.app.dto;

public class TeamRecordDTO {
//	CREATE TABLE TBL_TEAM_RECORD (
//	TEAM_NUMBER       NUMBER ,
//	SEASON_YEAR       NUMBER,
//	TEAM_RANK         NUMBER,
//	GAME_COUNT        NUMBER,
//	TEAM_WIN          NUMBER,
//	TEAM_DRAW         NUMBER,
//	TEAM_LOSE         NUMBER,
//	TEAM_WIN_RATE     NUMBER,
//	TEAM_AVG_BAT      NUMBER,
//	TEAM_ERA          NUMBER,
//	TEAM_SCORE        NUMBER,
//	TEAM_CONCEDE      NUMBER,
//	CONSTRAINT PK_TEAM_RECORD PRIMARY KEY (TEAM_NUMBER, SEASON_YEAR),
//	CONSTRAINT FK_TEAM_RECORD FOREIGN KEY (TEAM_NUMBER) REFERENCES TBL_TEAM(TEAM_NUMBER)
//	);
}
