/**
 * 
 */
package com.bullPenTalk.app.dto;

/**
 * 
 */
public class TeamPostDTO {
//	CREATE TABLE TBL_POST(
//			POST_NUMBER NUMBER,
//			MEMBER_NUMBER NUMBER,
//			TEAM_NUMBER NUMBER,
//			ADMIN_NUMBER NUMBER,
//			BOARD_ID NUMBER,
//			POST_TITLE VARCHAR2(100) NOT NULL,
//			POST_CONTENT CLOB NOT NULL,
//			POST_DATE DATE NOT NULL DEFAULT SYSDATE,
//			POST_UPDATE DATE,
//			POST_LINK VARCHAR2(200),
//			CONSTRAINT PK_POST PRIMARY KEY(POST_NUMBER),
//			CONSTRAINT FK_POST_MEMBER FOREIGN KEY(MEMBER_NUMBER) REFERENCES TBL_MEMBER(MEMBER_NUMBER) ON DELETE CASCADE,
//			CONSTRAINT FK_POST_TEAM FOREIGN KEY(TEAM_NUMBER) REFERENCES TBL_TEAM(TEAM_NUMBER),
//			CONSTRAINT FK_POST_ADMIN FOREIGN KEY(ADMIN_NUMBER) REFERENCES TBL_ADMIN(ADMIN_NUMBER),
//			CONSTRAINT fk_post_board FOREIGN key(board_id) REFERENCES TBL_BOARD (BOARD_NUMBER)
//			);
	
	private int postNumber;
	private int teamNumber;
	


}
