package com.bullPenTalk.app.dto;

public class TeamBatterRecordDTO {
//	CREATE TABLE TBL_TEAM_BATTER_RECORD (
//	TEAM_ID                   NUMBER NOT NULL,
//	SEASON_YEAR               NUMBER NOT NULL,
//	TEAM_BATTER_AVG_BAT       NUMBER,
//	TEAM_BATTER_GAME_COUNT    NUMBER,
//	TEAM_BATTER_AT_BAT        NUMBER,
//	TEAM_BATTER_RBI           NUMBER,
//	TEAM_BATTER_SCORE         NUMBER,
//	TEAM_BATTER_HITS          NUMBER,
//	TEAM_BATTER_DOUBLE_HIT    NUMBER,
//	TEAM_BATTER_TRIPLE_HIT    NUMBER,
//	TEAM_BATTER_HR            NUMBER,
//	TEAM_BATTER_BB            NUMBER,
//	TEAM_BATTER_GIDOUT        NUMBER,
//	TEAM_BATTER_HBP           NUMBER,
//	TEAM_BATTER_STRIKEOUT     NUMBER,
//	TEAM_BATTER_OPS           NUMBER,
//	TEAM_BATTER_STOLEN_BASE   NUMBER,
//	CONSTRAINT PK_TEAM_BATTER_RECORD PRIMARY KEY (TEAM_ID, SEASON_YEAR),
//	CONSTRAINT FK_TEAM_BATTER_RECORD FOREIGN KEY (TEAM_ID) REFERENCES TBL_TEAM(TEAM_NUMBER) ON DELETE CASCADE
//	);
}
