package com.bullPenTalk.app.dto;

public class TeamPitcherRecordDTO {
//	CREATE TABLE TBL_TEAM_PITCHER_RECORD (
//	TEAM_NUMBER                  NUMBER NOT NULL,
//	SEASON_YEAR                  NUMBER NOT NULL,
//	TEAM_PITCHER_ERA             NUMBER,
//	TEAM_PITCHER_START_ERA       NUMBER,
//	TEAM_PITCHER_RELIEF_ERA      NUMBER,
//	TEAM_PITCHER_GAME_COUNT      NUMBER,
//	TEAM_PITCHER_WIN             NUMBER,
//	TEAM_PITCHER_LOSE            NUMBER,
//	TEAM_PITCHER_SAVE            NUMBER,
//	TEAM_PITCHER_HOLD            NUMBER,
//	TEAM_PITCHER_STRIKEOUT       NUMBER,
//	TEAM_PITCHER_HITS            NUMBER,
//	TEAM_PITCHER_HR              NUMBER,
//	TEAM_PITCHER_BB              NUMBER,
//	TEAM_PITCHER_HBP             NUMBER,
//	TEAM_PITCHER_SCORE           NUMBER,
//	TEAM_PITCHER_SELF_SCORE      NUMBER,
//	CONSTRAINT PK_TEAM_PITCHER_RECORD PRIMARY KEY (TEAM_NUMBER, SEASON_YEAR),
//	CONSTRAINT FK_TEAM_PITCHER_RECORD FOREIGN KEY (TEAM_NUMBER) REFERENCES TBL_TEAM(TEAM_NUMBER)
//	);
}
